### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by andrevandal** [wobsoriano/v-dashboard#1]
Hi, I'm opening this issue only to thank you for this project!
I'm always looking for a TailwindCSS Dashboard and I'm in love with this project!

Thank you so much! <3

**Comment by wobsoriano** [comment]
Thanks! The original dashboard is this https://github.com/tailwindcomponents/dashboard and I just converted it to Vue 3 :)

**Comment by vingojw** [comment]
Thanks again! :)
