### ISSUE TITLE
How to add 3rd Party Packages?

### ISSUE THREAD

**Issue by colodenn** [wobsoriano/v-dashboard#2]
Hello wobsoriano,

It seems like I can't add any 3rd Party Packages to your Dashboard.

**Comment by wobsoriano** [comment]
Hi, what module are you trying to install?

**Comment by colodenn** [comment]
'vue-notifications' for example

**Comment by wobsoriano** [comment]
> 'vue-notifications' for example

vue-notifications is not compatible with Vue 3 Composition API
