### ISSUE TITLE
Sidebar shouldn't be clickable when modal is open

### ISSUE THREAD

**Issue by wobsoriano** [wobsoriano/v-dashboard#5]
When you open a modal, the sidebar is still clickable; hence letting you navigate away without closing the modal.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/13049130/94982475-427d1580-056d-11eb-9fb1-6c2a6fefdfcd.gif)

**Comment by sebassu** [comment]
Hello, I'd like to be assigned to this issue if possible.

**Comment by wobsoriano** [comment]
> Hello, I'd like to be assigned to this issue if possible.

Assigned you. Thanks!

**Comment by jovi09** [comment]
Hey I would like to work on this issue

**Comment by geeks5551** [comment]
hey can i be assigned above issue ? looking interesting to  solve
