### ISSUE TITLE
How to add modules like strapi-module?

### ISSUE THREAD

**Issue by colodenn** [wobsoriano/v-dashboard#7]
I followed the instructions https://strapi.nuxtjs.org/setup.
But I cant reference strapi in my project.

**Comment by wobsoriano** [comment]
That is a Nuxt module which is not compatible with Vite.

Also, Vite uses Vue 3, so I doubt it would even work on a Vue 3 app.

**Comment by wobsoriano** [comment]
That is a Nuxt module which is not compatible with Vite.

Also, Vite uses Vue 3, so I doubt it would even work on a Vue 3 app.

What you can do is create a Nuxt app, install [tailwind](https://tailwindcss.nuxtjs.org/tailwind-config/), then copy the elements you want in this repo.
